import { cloudConfigured, currentCloudAccount, signIn, signOutCloud, loadCloudData, createAbsenceRequest, reviewAbsenceRequest, createTrackingItem, signedDocumentUrl, uploadStudentPhoto, supabase } from "./cloud.js";

const EMPTY_STATE = { students: [], observations: [], sanctions: [] };
const STAFF = {
  coach: ["Valentine Delaveau", "Patrice Delaveau", "Antoine", "Bertrand Lebarbier"],
  admin: ["Sabrine Delaveau", "Norman"]
};

if (localStorage.getItem("delaveau-data-version") !== "2") {
  localStorage.removeItem("delaveau-state");
  localStorage.removeItem("delaveau-session");
  localStorage.setItem("delaveau-data-version", "2");
}

function readSessionCookie() { try { const item=document.cookie.split("; ").find(row=>row.startsWith("delaveau_session=")); return item?JSON.parse(decodeURIComponent(item.split("=").slice(1).join("="))):null; } catch { return null; } }
function persistSession(user) { localStorage.setItem("delaveau-session",JSON.stringify(user)); document.cookie=`delaveau_session=${encodeURIComponent(JSON.stringify(user))}; Max-Age=31536000; Path=/application-academie-delaveau/; SameSite=Lax; Secure`; }
function clearPersistentSession() { localStorage.removeItem("delaveau-session"); document.cookie="delaveau_session=; Max-Age=0; Path=/application-academie-delaveau/; SameSite=Lax; Secure"; }

let state = loadJSON("delaveau-state", EMPTY_STATE);
state.absences ||= [];
state.delays ||= [];
state.monthlyObservations ||= [];
state.notifications ||= [];
let parentAccounts = loadJSON("delaveau-parent-accounts", []);
let currentUser = loadJSON("delaveau-session", null) || readSessionCookie();
let currentRole = currentUser?.role || null;
let currentView = "dashboard";
let selectedStudent = null;
let signup = { step: 0, data: {} };
let tourIndex = 0;

const app = document.querySelector("#app");
const nav = document.querySelector("#main-nav");
const modal = document.querySelector("#modal-backdrop");
const authScreen = document.querySelector("#auth-screen");
const icons = { dashboard: "⌂", absences: "○", delays: "◷", monthly: "✎", students: "♙", entry: "+", request: "+", notifications: "♢" };
const staffNav = [["dashboard","Accueil"],["students","Élèves"],["entry","Saisir"],["notifications","Alertes"]];
const studentNav = [["dashboard","Mon suivi"],["absences","Absences"],["delays","Retards"],["monthly","Bilan"],["request","Prévenir"]];
const parentNav = [["dashboard","Suivi"],["absences","Absences"],["delays","Retards"],["monthly","Bilan"]];
const adminNav = staffNav;
const signupSteps = [
  { key: "firstName", title: "Quel est ton prénom ?", hint: "Le prénom utilisé au sein de l’Académie.", type: "text", placeholder: "Ton prénom" },
  { key: "lastName", title: "Quel est ton nom ?", hint: "Il restera visible uniquement par l’équipe autorisée.", type: "text", placeholder: "Ton nom" },
  { key: "birthDate", title: "Quelle est ta date de naissance ?", hint: "Elle nous permet de sécuriser ton dossier.", type: "date" },
  { key: "group", title: "Quelle section vas-tu rejoindre ?", hint: "Choisis ton parcours actuel.", options: ["Section Excellence", "Section Espoir"] },
  { key: "horse", title: "Quel est le nom de ton cheval ?", hint: "Tu peux écrire « Aucun » si tu n’en as pas encore.", type: "text", placeholder: "Nom du cheval" },
  { key: "horseAge", title: "Quel âge a ton cheval ?", hint: "Indique son âge actuel en années.", type: "number", placeholder: "Par exemple : 9" },
  { key: "horseHeight", title: "Quelle est sa taille ?", hint: "Indique sa taille au garrot en centimètres.", type: "number", placeholder: "Par exemple : 168" },
  { key: "horsePartnership", title: "Depuis combien de temps évoluez-vous ensemble ?", hint: "Indique la durée de votre expérience en couple.", type: "text", placeholder: "Par exemple : 2 ans" },
  { key: "horseExperience", title: "Quelle est la plus grande épreuve déjà sautée ensemble ?", hint: "Précise le niveau, la hauteur ou l’intitulé de l’épreuve.", type: "text", placeholder: "Par exemple : Grand Prix 1,20 m" },
  { key: "photo", title: "Ajoute une photo de profil", hint: "Facultatif · ton visage sera visible uniquement par les personnes autorisées.", type: "file", optional: true },
  { key: "email", title: "Quelle est ton adresse e-mail ?", hint: "Elle servira à retrouver ton compte.", type: "email", placeholder: "prenom@exemple.fr" },
  { key: "password", title: "Choisis un mot de passe", hint: "Au moins 6 caractères pour ce prototype.", type: "password", placeholder: "••••••••" }
];

function loadJSON(key, fallback) { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : structuredClone(fallback); } catch { return structuredClone(fallback); } }
function save() { localStorage.setItem("delaveau-state", JSON.stringify(state)); }
function student(id) { return state.students.find(s => String(s.id) === String(id)); }
function mapCloudData(data) { return {students:data.students.map(s=>({id:s.id,userId:s.user_id,name:s.full_name,initials:initials(s.full_name),photoUrl:s.photo_url||null,group:s.academy_group||"Section non renseignée",birthDate:s.birth_date,horse:s.horse_name,horseAge:s.horse_age,horseHeight:s.horse_height,horsePartnership:s.horse_partnership,horseExperience:s.horse_experience,incidents:0})),observations:[],sanctions:[],absences:data.absences.map(x=>({id:x.id,studentId:x.student_id,date:x.absence_date,createdAt:x.created_at,text:x.reason,reason:x.reason,justification:x.document_name||"Aucun justificatif",documentPath:x.document_path,documentType:x.document_type,source:"student",status:x.status==="pending"?"À vérifier":x.status==="approved"?"Validée":"Refusée"})),delays:data.delays.map(x=>({id:x.id,studentId:x.student_id,date:x.occurred_on,text:x.details,reason:x.details,source:"staff",status:"Validée"})),monthlyObservations:data.monthly.map(x=>({id:x.id,studentId:x.student_id,date:x.month,month:x.month.slice(0,7),text:x.details,source:"staff",status:"Validée"})),notifications:[]}; }
async function refreshCloudState(){if(!cloudConfigured)return;const data=await loadCloudData();state=mapCloudData(data);save();}
function initials(name) { return name.split(" ").filter(Boolean).map(x => x[0]).join("").slice(0,2).toUpperCase(); }
function studentPortrait(s,className="") { return s?.photoUrl?`<img class="student-photo ${className}" src="${s.photoUrl}" alt="Photo de ${s.name}">`:`<span class="avatar ${className}">${s?.initials||"?"}</span>`; }
function dateFR(date) { return new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short", year: "numeric" }).format(new Date(date + "T12:00:00")); }
function todayISO() { return new Date().toISOString().slice(0,10); }
function statusFor(count) { return count >= 3 ? ["alert","Action requise"] : count > 0 ? ["watch","À surveiller"] : ["good","À jour"]; }
function toast(message) { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2600); }
function emptyBlock(icon, title, text) { return `<div class="empty"><div style="font-size:34px;color:var(--forest)">${icon}</div><h2>${title}</h2><p>${text}</p></div>`; }

function renderAuthLanding() {
  document.body.classList.add("auth-active"); authScreen.classList.remove("hidden");
  authScreen.innerHTML=`<div class="auth-landing"><img src="/assets/logo-academie-delaveau.png" alt="Académie Delaveau"><div class="auth-landing-actions"><button class="primary-button" id="auth-signup">S’inscrire</button><button class="secondary-button" id="auth-login">Se connecter</button></div></div>`;
  document.querySelector("#auth-signup").onclick=renderSignupChoice;
  document.querySelector("#auth-login").onclick=()=>renderAuthHome("login");
}
function renderSignupChoice() {
  authScreen.innerHTML=`<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><img class="auth-logo" src="/assets/logo-academie-delaveau.png" alt="Académie Delaveau"><div class="auth-heading"><span class="eyebrow">Inscription</span><h1>Créer un compte</h1><p>Qui souhaitez-vous inscrire ?</p></div><div class="role-choices signup-role-choices"><button class="auth-choice" id="signup-student"><span class="auth-choice-icon">♘</span><strong>Élève</strong><small>Créer mon dossier</small></button><button class="auth-choice" id="signup-parent"><span class="auth-choice-icon">♧</span><strong>Parent</strong><small>Lier mon enfant</small></button></div></div>`;
  document.querySelector("#auth-back").onclick=renderAuthLanding;
  document.querySelector("#signup-student").onclick=()=>{signup={step:0,data:{}};renderSignup();};
  document.querySelector("#signup-parent").onclick=()=>renderParentAccess("create");
}
function renderAuthHome() {
  document.body.classList.add("auth-active"); authScreen.classList.remove("hidden");
  authScreen.innerHTML = `<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><img class="auth-logo" src="/assets/logo-academie-delaveau.png" alt="Académie Delaveau"><div class="auth-heading"><span class="eyebrow">Connexion</span><h1>Je suis…</h1><p>Choisissez votre espace pour continuer.</p></div><div class="role-choices"><button class="auth-choice" data-auth-role="student"><span class="auth-choice-icon">♘</span><strong>Élève</strong><small>Ouvrir mon suivi</small></button><button class="auth-choice" data-auth-role="parent"><span class="auth-choice-icon">♧</span><strong>Parent</strong><small>Suivre mon enfant</small></button><button class="auth-choice" data-auth-role="coach"><span class="auth-choice-icon">♙</span><strong>Coach</strong><small>Accéder au suivi</small></button><button class="auth-choice" data-auth-role="admin"><span class="auth-choice-icon">⚙</span><strong>Admin</strong><small>Gérer l’Académie</small></button></div></div>`;
  document.querySelector("#auth-back").onclick=renderAuthLanding;
  authScreen.querySelectorAll("[data-auth-role]").forEach(button => button.onclick = () => { const role = button.dataset.authRole; if (role === "student") renderStudentLogin(); else if (role === "parent") renderParentAccess(); else renderStaffChoice(role); });
}
function renderStudentLogin() {
  authScreen.innerHTML=`<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><section class="signup-card"><div class="auth-heading"><span class="eyebrow">Espace élève</span><h1>Connexion</h1><p>Utilise les identifiants choisis lors de ton inscription.</p></div><form id="student-login-form" class="form-grid"><div class="field"><label for="student-email">Adresse e-mail</label><input id="student-email" type="email" required placeholder="eleve@exemple.fr"></div><div class="field"><label for="student-password">Mot de passe</label><input id="student-password" type="password" required placeholder="Ton mot de passe"></div><button class="primary-button">Se connecter</button></form></section></div>`;
  document.querySelector("#auth-back").onclick=()=>renderAuthHome("login");
  document.querySelector("#student-login-form").onsubmit=async event=>{
    event.preventDefault();
    const form=event.currentTarget,submit=form.querySelector("button[type='submit'], button:not([type])");
    const email=document.querySelector("#student-email").value.trim().toLowerCase(),password=document.querySelector("#student-password").value;
    submit.disabled=true; submit.textContent="Connexion…";
    try{
      if(cloudConfigured){
        const {user}=await signIn(email,password);
        const account=await currentCloudAccount();
        if(!account?.profile)throw new Error("Votre profil n’est pas encore configuré");
        if(account.profile.role!=="student")throw new Error("Ce compte n’est pas un compte élève");
        await refreshCloudState();
        const pupil=state.students.find(s=>s.userId===user.id);
        if(!pupil)throw new Error("Fiche élève introuvable");
        login({name:pupil.name,role:"student",initials:pupil.initials,studentId:pupil.id,userId:user.id});
        return;
      }
      const account=state.students.find(s=>(s.email||"").toLowerCase()===email&&s.password===password);
      if(!account)throw new Error("E-mail ou mot de passe incorrect");
      login({name:account.name,role:"student",initials:account.initials,studentId:account.id});
    }catch(error){
      console.error("Student sign in",error);
      toast(error.message||"Connexion impossible");
      submit.disabled=false; submit.textContent="Se connecter";
    }
  };
}
function childOptions() { return state.students.length ? state.students.map(s=>`<option value="${s.id}">${s.name} · ${s.group}</option>`).join("") : `<option value="">Aucun élève inscrit</option>`; }
function renderParentAccess(mode="login") {
  const isCreate=mode==="create";
  authScreen.innerHTML = `<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><section class="signup-card"><div class="auth-heading"><span class="eyebrow">Espace parent</span><h1>${isCreate?"Créer mon compte":"Connexion parent"}</h1><p>Sélectionnez votre enfant puis utilisez vos identifiants personnels.</p></div><div class="auth-tabs"><button class="${!isCreate?'active':''}" data-parent-mode="login">Se connecter</button><button class="${isCreate?'active':''}" data-parent-mode="create">Créer un compte</button></div><form id="parent-form" class="form-grid">${isCreate?`<div class="field"><label for="parent-name">Votre nom et prénom</label><input id="parent-name" required placeholder="Sophie Martin"></div>`:""}<div class="field"><label for="parent-child">Mon enfant</label><select id="parent-child" required>${childOptions()}</select></div><div class="field"><label for="parent-email">Votre adresse e-mail</label><input id="parent-email" type="email" required placeholder="parent@exemple.fr"></div><div class="field"><label for="parent-password">Votre mot de passe</label><input id="parent-password" type="password" minlength="6" required placeholder="6 caractères minimum"></div><button class="primary-button" ${state.students.length?"":"disabled"}>${isCreate?"Créer mon compte":"Se connecter"}</button></form>${state.students.length?"":`<p class="auth-notice">Un élève doit d’abord créer son compte pour apparaître dans cette liste.</p>`}</section></div>`;
  document.querySelector("#auth-back").onclick = isCreate ? renderSignupChoice : ()=>renderAuthHome("login");
  document.querySelectorAll("[data-parent-mode]").forEach(button=>button.onclick=()=>renderParentAccess(button.dataset.parentMode));
  document.querySelector("#parent-form").onsubmit = event => {
    event.preventDefault(); const studentId=Number(document.querySelector("#parent-child").value), email=document.querySelector("#parent-email").value.trim().toLowerCase(), password=document.querySelector("#parent-password").value;
    if(isCreate){ if(parentAccounts.some(account=>account.email===email))return toast("Un compte parent existe déjà avec cet e-mail"); const name=document.querySelector("#parent-name").value.trim(); const account={id:Date.now(),name,email,password,studentId}; parentAccounts.push(account); localStorage.setItem("delaveau-parent-accounts",JSON.stringify(parentAccounts)); login({name,role:"parent",initials:initials(name),studentId}); return; }
    const account=parentAccounts.find(item=>item.email===email&&item.password===password&&item.studentId===studentId); if(!account)return toast("Enfant, e-mail ou mot de passe incorrect"); login({name:account.name,role:"parent",initials:initials(account.name),studentId:account.studentId});
  };
}
function renderStaffChoice(role) {
  const title = role === "coach" ? "Quel coach êtes-vous ?" : "Quel administrateur êtes-vous ?";
  authScreen.innerHTML = `<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><div class="auth-heading"><span class="eyebrow">Espace ${role === "coach" ? "coach" : "administration"}</span><h1>${title}</h1><p>Sélectionnez votre profil.</p></div><div class="person-choices">${STAFF[role].map(name => `<button class="person-choice" data-person="${name}"><span class="avatar">${initials(name)}</span><span><strong>${name}</strong><small>${role === "coach" ? "Coach Académie" : "Administrateur"}</small></span></button>`).join("")}</div></div>`;
  document.querySelector("#auth-back").onclick = renderAuthHome;
  authScreen.querySelectorAll("[data-person]").forEach(button => button.onclick = () => cloudConfigured?renderStaffLogin(role,button.dataset.person):login({ name: button.dataset.person, role, initials: initials(button.dataset.person), studentId: null }));
}
function renderStaffLogin(role,name){authScreen.innerHTML=`<div class="auth-wrap"><button class="auth-back" id="auth-back">← Retour</button><section class="signup-card"><div class="auth-heading"><span class="eyebrow">${role==="coach"?"Coach":"Administration"}</span><h1>${name}</h1><p>Utilisez les identifiants sécurisés de votre compte équipe.</p></div><form id="staff-login-form" class="form-grid"><div class="field"><label>Adresse e-mail</label><input id="staff-email" type="email" required></div><div class="field"><label>Mot de passe</label><input id="staff-password" type="password" required></div><button class="primary-button">Se connecter</button></form></section></div>`;document.querySelector("#auth-back").onclick=()=>renderStaffChoice(role);document.querySelector("#staff-login-form").onsubmit=async e=>{e.preventDefault();try{await signIn(document.querySelector("#staff-email").value.trim(),document.querySelector("#staff-password").value);const account=await currentCloudAccount();if(account.profile.role!==role||account.profile.full_name!==name){await signOutCloud();throw new Error("Ce compte ne correspond pas au profil sélectionné");}await refreshCloudState();login({name,role,initials:initials(name),studentId:null,userId:account.profile.id});}catch(error){toast(error.message||"Connexion impossible");}};}
function renderSignup() {
  const step = signupSteps[signup.step], value = signup.data[step.key] || "", progress = Math.round(((signup.step + 1) / signupSteps.length) * 100);
  const control=step.options?`<div class="signup-options">${step.options.map(option=>`<button type="button" class="signup-option ${value===option?"selected":""}" data-option="${option}">${option}</button>`).join("")}</div>`:step.type==="file"?`<div class="signup-photo"><div class="signup-photo-preview" id="signup-photo-preview">${signup.data.photoPreview?`<img src="${signup.data.photoPreview}" alt="Aperçu de la photo">`:`<span>♙</span><small>Aucune photo</small>`}</div><input id="signup-value" type="file" accept="image/jpeg,image/png,image/webp"><label for="signup-value">${signup.data.photo?"Changer la photo":"Choisir une photo"}</label><small>JPG, PNG ou WebP · 5 Mo maximum</small></div>`:`<input class="signup-input" id="signup-value" type="${step.type}" value="${value}" placeholder="${step.placeholder||""}" autocomplete="${step.type==="password"?"new-password":"off"}" required>`;
  authScreen.innerHTML=`<div class="auth-wrap"><button class="auth-back" id="auth-back">← ${signup.step?"Question précédente":"Retour"}</button><section class="signup-card"><div class="signup-meta"><span>Création du compte</span><span>${signup.step+1}/${signupSteps.length}</span></div><div class="signup-progress" style="--signup-progress:${progress}%"><span></span></div><form id="signup-form"><div class="signup-question"><h2>${step.title}</h2><p>${step.hint}</p>${control}</div><div class="signup-actions"><span style="color:var(--muted);font-size:12px">${progress}% complété</span><button class="primary-button">${signup.step===signupSteps.length-1?"Créer mon compte":step.type==="file"&&!signup.data.photo?"Continuer sans photo":"Continuer →"}</button></div></form></section></div>`;
  document.querySelector("#auth-back").onclick = () => { if (signup.step === 0) renderSignupChoice(); else { signup.step--; renderSignup(); } };
  document.querySelectorAll("[data-option]").forEach(button => button.onclick = () => { signup.data[step.key] = button.dataset.option; document.querySelectorAll("[data-option]").forEach(x => x.classList.remove("selected")); button.classList.add("selected"); });
  if(step.type==="file")document.querySelector("#signup-value").onchange=event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){event.target.value="";return toast("La photo doit faire moins de 5 Mo");}signup.data.photo=file;signup.data.photoPreview=URL.createObjectURL(file);renderSignup();};
  document.querySelector("#signup-form").onsubmit=async event=>{event.preventDefault();if(!step.options&&step.type!=="file")signup.data[step.key]=document.querySelector("#signup-value").value.trim();if(!step.optional&&!signup.data[step.key])return toast("Merci de répondre avant de continuer");if(step.key==="password"&&signup.data.password.length<6)return toast("Le mot de passe doit contenir 6 caractères minimum");if(signup.step<signupSteps.length-1){signup.step++;renderSignup();return;}const name=`${signup.data.firstName} ${signup.data.lastName}`;if(cloudConfigured){try{const {data,error}=await supabase.auth.signUp({email:signup.data.email,password:signup.data.password,options:{data:{role:"student",full_name:name,birth_date:signup.data.birthDate,academy_group:signup.data.group,horse_name:signup.data.horse,horse_age:Number(signup.data.horseAge),horse_height:Number(signup.data.horseHeight),horse_partnership:signup.data.horsePartnership,horse_experience:signup.data.horseExperience}}});if(error)throw error;if(!data.session){toast("Compte créé : confirmez votre adresse e-mail");return renderStudentLogin();}if(signup.data.photo)await uploadStudentPhoto(data.user.id,signup.data.photo);await refreshCloudState();const pupil=state.students.find(s=>s.userId===data.user.id);login({name,role:"student",initials:initials(name),studentId:pupil.id,userId:data.user.id});}catch(error){toast(error.message||"Inscription impossible");}return;}const photoUrl=signup.data.photo?await readFileData(signup.data.photo):null;const newStudent={id:Date.now(),name,initials:initials(name),photoUrl,group:signup.data.group,horse:signup.data.horse,horseAge:Number(signup.data.horseAge),horseHeight:Number(signup.data.horseHeight),horsePartnership:signup.data.horsePartnership,horseExperience:signup.data.horseExperience,incidents:0,birthDate:signup.data.birthDate,email:signup.data.email,password:signup.data.password};state.students.push(newStudent);save();login({name,role:"student",initials:newStudent.initials,studentId:newStudent.id});};
  setTimeout(() => document.querySelector("#signup-value")?.focus(), 100);
}
function login(user) { currentUser = user; currentRole = user.role; currentView = "dashboard"; selectedStudent = null; persistSession(user); document.body.classList.remove("auth-active"); authScreen.classList.add("hidden"); render(); setTimeout(() => maybeStartTour(), 500); }
async function logout() { closeModal(); closeTour(false);if(cloudConfigured)await signOutCloud(); clearPersistentSession(); currentUser = null; currentRole = null; renderAuthLanding(); }
function setProfile() { if (!currentUser) return; document.querySelector("#profile-name").textContent = currentUser.name; document.querySelector("#profile-role").textContent = currentRole === "admin" ? "Administrateur" : currentRole === "coach" ? "Coach" : currentRole === "parent" ? "Parent" : "Élève"; document.querySelector("#profile-avatar").textContent = currentUser.initials; }
function renderNav() { if (!currentUser) return; const items = currentRole === "admin" ? adminNav : currentRole === "coach" ? staffNav : currentRole === "parent" ? parentNav : studentNav; const roleLabel = currentRole === "admin" ? "Administration" : currentRole === "coach" ? "Coach" : currentRole === "parent" ? "Parent" : "Élève"; const unread=state.notifications.filter(n=>!n.read).length; nav.innerHTML = `<div class="nav-label">Espace ${roleLabel}</div>` + items.map(([id,label]) => `<button class="nav-item ${currentView === id ? "active" : ""}" data-view="${id}"><span class="nav-icon">${icons[id]}</span>${label}${id==='notifications'&&unread?`<b class="nav-badge">${unread}</b>`:""}</button>`).join(""); nav.querySelectorAll("[data-view]").forEach(button => button.onclick = () => { currentView = button.dataset.view; selectedStudent = null; render(); }); }

function statCard(label, value, note, accent="#23579a") { return `<article class="card stat-card" style="--accent:${accent}"><div class="stat-top"><span>${label}</span><span>↗</span></div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></article>`; }
function heading(kicker, title, subtitle, action="") { return `<div class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`; }
function studentRow(s) {
  const abs=countFor(state.absences,s.id), delays=countFor(state.delays,s.id), reports=countFor(state.monthlyObservations,s.id);
  return `<article class="student-card-modern" data-student="${s.id}"><div class="student-card-visual">${studentPortrait(s,"student-card-photo")}<span class="student-group-badge">${s.group.replace("Section ","")}</span></div><div class="student-card-body"><h2>${s.name}</h2><p class="student-card-group">${s.group}</p><div class="student-horse"><span>♘</span><div><small>Cheval partenaire</small><strong>${s.horse||"Non renseigné"}</strong><em>${s.horseExperience||"Niveau non renseigné"}</em></div></div><div class="student-kpis"><span><b>${abs}</b><small>Absences</small></span><span><b>${delays}</b><small>Retards</small></span><span><b>${reports}</b><small>Bilans</small></span></div><button class="student-open" aria-label="Ouvrir la fiche de ${s.name}">Ouvrir la fiche <b>→</b></button></div></article>`;
}

function renderStaffDashboard() {
  const incidentTotal = state.students.reduce((n,s)=>n+s.incidents,0), alerts = state.students.filter(s=>s.incidents>=3).length, recent = [...state.observations].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4), firstName = currentUser.name.split(" ")[0];
  app.innerHTML = heading("Aujourd’hui", `Bonjour ${firstName}`, currentRole === "admin" ? "Pilotez la vie de l’Académie depuis votre espace." : "Voici l’essentiel de la vie de l’Académie aujourd’hui.", `<button class="primary-button" id="add-observation">+ Nouvelle observation</button>`) + `<section class="grid stats" id="dashboard-stats">${statCard("Académiciens",state.students.length,state.students.length ? "inscrits dans l’application" : "aucun compte élève")}${statCard("Incidents actifs",incidentTotal,"sur la période en cours","#b74d47")}${statCard("Alertes au seuil",alerts,"validation humaine requise","#c77d32")}${statCard("Présences","—","aucune présence saisie","#6f8aa1")}</section><section class="grid dashboard-grid"><article class="card section-card"><div class="section-head"><div><span class="eyebrow">Suivi</span><h2>Académiciens à surveiller</h2></div><a href="#" data-goto="students">Voir tous</a></div><div class="student-list">${state.students.filter(s=>s.incidents>0).sort((a,b)=>b.incidents-a.incidents).map(studentRow).join("") || emptyBlock("♙","Tout va bien","Aucun incident actif pour le moment.")}</div></article><article class="card section-card"><div class="section-head"><div><span class="eyebrow">Activité</span><h2>Dernières notes</h2></div></div><div class="timeline">${recent.map(o=>{const s=student(o.studentId);return s ? `<div class="timeline-item"><span class="timeline-icon">${o.incident?'!':'✓'}</span><div><strong>${s.name}</strong><p>${o.type} · ${o.text}</p><small>${dateFR(o.date)} · ${o.coach}</small></div></div>` : ""}).join("") || emptyBlock("✎","Aucune note","Les nouvelles observations apparaîtront ici.")}</div></article></section>`;
  document.querySelector("#add-observation").onclick = openObservationModal; bindStudentRows(); document.querySelector("[data-goto]").onclick = event => { event.preventDefault(); currentView="students"; render(); };
}
function renderStudents() {
  app.innerHTML=heading("Effectif","Fiches élèves","Retrouvez rapidement un élève, son cheval et les éléments essentiels de son suivi.",`<button class="primary-button" id="new-entry">+ Ajouter au suivi</button>`)+`<section class="student-toolbar"><label class="student-search"><span>⌕</span><input id="student-search-input" type="search" placeholder="Rechercher un élève ou un cheval…" aria-label="Rechercher un élève"></label><select id="student-group-filter" aria-label="Filtrer par groupe"><option value="">Tous les groupes · ${state.students.length}</option>${[...new Set(state.students.map(s=>s.group).filter(Boolean))].map(group=>`<option value="${group}">${group}</option>`).join("")}</select></section><div class="student-list student-directory" id="all-students">${state.students.map(studentRow).join("")||emptyBlock("♘","Aucun élève inscrit","Les élèves apparaîtront ici après la création de leur compte.")}</div>`;
  const updateList=()=>{const query=document.querySelector("#student-search-input").value.trim().toLowerCase(),group=document.querySelector("#student-group-filter").value;const list=state.students.filter(s=>(!group||s.group===group)&&(!query||`${s.name} ${s.horse||""}`.toLowerCase().includes(query)));document.querySelector("#all-students").innerHTML=list.map(studentRow).join("")||emptyBlock("⌕","Aucun résultat","Essayez un autre nom, cheval ou groupe.");bindStudentRows();};
  document.querySelector("#new-entry").onclick=()=>openStaffEntryModal();document.querySelector("#student-search-input").oninput=updateList;document.querySelector("#student-group-filter").onchange=updateList;bindStudentRows();
}
function renderStudentDetail(id, own=false) {
  const s=student(id); if (!s) return renderMissingStudent(); const obs=state.observations.filter(o=>o.studentId===s.id).sort((a,b)=>b.date.localeCompare(a.date)), sanction=state.sanctions.find(x=>x.studentId===s.id);
  app.innerHTML = `${own ? heading("Mon espace", s.name, "Un suivi sportif et éducatif clair.") : `<button class="ghost-button" id="back">← Retour aux académiciens</button><br><br>`}<section class="card detail-hero"><div class="detail-person"><span class="avatar">${s.initials}</span><div><h2>${s.name}</h2><p>${s.group} · Cheval : ${s.horse || "Non renseigné"}</p><span class="status ${statusFor(s.incidents)[0]}">${statusFor(s.incidents)[1]}</span></div></div><div style="display:flex;align-items:center;gap:12px"><div><strong>Seuil d’incidents</strong><small style="display:block;color:var(--muted)">Une décision reste toujours humaine</small></div><div class="progress-ring" style="--progress:${Math.min(100,s.incidents/3*100)}"><strong>${s.incidents}/3</strong></div></div></section>${sanction ? `<div class="sanction-banner"><strong>⚑ ${sanction.title} — ${sanction.status}</strong><p>${sanction.reason}.</p>${currentRole!=='student'&&sanction.status==='À valider'?`<button class="primary-button" id="validate-sanction">Valider la décision</button>`:""}</div>`:""}<section class="grid two-cols"><article class="card section-card"><div class="section-head"><h2>Journal de suivi</h2>${currentRole!=='student'?`<button class="primary-button" id="add-observation">+ Ajouter</button>`:""}</div>${obs.map(o=>`<div class="observation"><div class="observation-head"><strong>${o.type}</strong><span class="status ${o.incident?'alert':'good'}">${o.incident?'Incident':'Positif'}</span></div><p>${o.text}</p><small>${dateFR(o.date)} · ${o.coach}</small></div>`).join("") || emptyBlock("✎","Aucune observation","Ton journal de suivi est encore vide.")}</article><article class="card section-card"><div class="section-head"><h2>Présence</h2></div>${emptyBlock("◷","Aucune donnée","Les présences et retards apparaîtront ici.")}<div><h2 style="font-size:18px">Règle de suivi</h2><p style="color:var(--muted);line-height:1.6;font-size:14px">À trois incidents actifs, l’application propose une mesure éducative. Le contexte est toujours examiné avant validation.</p></div></article></section>`;
  document.querySelector("#back")?.addEventListener("click",()=>{selectedStudent=null;currentView="students";render();}); document.querySelector("#add-observation")?.addEventListener("click",()=>openObservationModal(s.id)); document.querySelector("#validate-sanction")?.addEventListener("click",()=>{sanction.status="Validée";save();toast("Décision validée");render();});
}
function renderMissingStudent() { app.innerHTML = heading("Mon espace","Compte élève introuvable","Reconnectez-vous ou recréez votre compte.") + `<button class="primary-button" id="missing-logout">Revenir à la connexion</button>`; document.querySelector("#missing-logout").onclick=logout; }

function renderGeneric(type) {
  const filteredObs = currentRole === "student" ? state.observations.filter(o=>o.studentId===currentUser.studentId) : state.observations, filteredSanctions = currentRole === "student" ? state.sanctions.filter(x=>x.studentId===currentUser.studentId) : state.sanctions;
  const observations = filteredObs.map(o=>{const s=student(o.studentId);return s ? `<div class="observation"><div class="observation-head"><strong>${s.name} · ${o.type}</strong><span class="status ${o.incident?'alert':'good'}">${o.incident?'Incident':'Positif'}</span></div><p>${o.text}</p><small>${dateFR(o.date)} · ${o.coach}</small></div>` : ""}).join("");
  const content = { observations:["Observations","Les notes pédagogiques et sportives.",observations||emptyBlock("✎","Aucune observation","Le journal est vide pour le moment.")], attendance:["Présences","Les absences et retards enregistrés.",emptyBlock("◷","Aucune présence saisie","Les présences seront affichées dès leur premier enregistrement.")], sanctions:["Décisions éducatives","Les mesures proposées et validées.",filteredSanctions.map(x=>{const s=student(x.studentId);return s?`<div class="sanction-banner"><strong>${s.name} · ${x.title}</strong><p>${x.reason}</p><span class="status ${x.status==='Validée'?'good':'watch'}">${x.status}</span></div>`:""}).join("")||emptyBlock("⚑","Aucune décision","Aucune mesure éducative en cours.")], messages:["Messagerie","Les échanges avec l’équipe et les élèves.",emptyBlock("◇","Aucun message","Vos nouvelles conversations apparaîtront ici.")], admin:["Réglages","Gestion de l’application et des accès.",`<div class="grid two-cols">${statCard("Coachs",STAFF.coach.length,"profils préconfigurés")}${statCard("Administrateurs",STAFF.admin.length,"accès de gestion")}</div><div style="margin-top:24px"><h2>Comptes élèves</h2><p style="color:var(--muted)">${state.students.length} compte(s) créé(s) sur cet appareil.</p></div>`] }[type];
  app.innerHTML = heading("Académie Delaveau",content[0],content[1],currentRole!=="student"&&type==="observations"?`<button class="primary-button" id="add-observation">+ Nouvelle observation</button>`:"") + `<section class="card section-card">${content[2]}</section>`; document.querySelector("#add-observation")?.addEventListener("click",openObservationModal);
}
function openObservationModal(preselect="") {
  if (!state.students.length) return toast("Aucun élève n’est encore inscrit");
  document.querySelector("#modal-content").innerHTML = `<span class="eyebrow">Journal de suivi</span><h2 id="modal-title">Nouvelle observation</h2><p class="modal-intro">Rédigez une note factuelle et précise.</p><form id="observation-form" class="form-grid"><div class="field"><label for="student">Académicien</label><select id="student" required>${state.students.map(s=>`<option value="${s.id}" ${s.id===Number(preselect)?'selected':''}>${s.name}</option>`).join("")}</select></div><div class="field"><label for="type">Type</label><select id="type"><option>Progrès</option><option>Comportement</option><option>Retard</option><option>Absence</option><option>Travail</option><option>Santé</option></select></div><div class="field"><label for="note">Observation</label><textarea id="note" required placeholder="Décrivez les faits, sans jugement…"></textarea></div><label class="checkbox"><input id="incident" type="checkbox"> <span>Compter comme incident actif. Au troisième incident, une mesure éducative sera proposée.</span></label><div class="form-actions"><button type="button" class="ghost-button" id="cancel-modal">Annuler</button><button class="primary-button">Enregistrer</button></div></form>`;
  modal.classList.remove("hidden"); document.querySelector("#cancel-modal").onclick=closeModal; document.querySelector("#observation-form").onsubmit=event=>{ event.preventDefault(); const sid=Number(document.querySelector("#student").value), isIncident=document.querySelector("#incident").checked; state.observations.unshift({id:Date.now(),studentId:sid,type:document.querySelector("#type").value,date:todayISO(),text:document.querySelector("#note").value.trim(),coach:currentUser.name,incident:isIncident}); if(isIncident){const s=student(sid);s.incidents++;if(s.incidents>=3&&!state.sanctions.some(x=>x.studentId===sid&&x.status==='À valider'))state.sanctions.push({id:Date.now()+1,studentId:sid,status:"À valider",title:"Mesure éducative à définir",reason:"Seuil de 3 incidents actifs atteint"});} save();closeModal();toast(isIncident&&student(sid).incidents>=3?"Seuil atteint : décision à examiner":"Observation enregistrée");render(); };
}
function openAccountModal() { document.querySelector("#modal-content").innerHTML=`<span class="eyebrow">Mon compte</span><h2 id="modal-title">${currentUser.name}</h2><p class="modal-intro">${currentRole === "admin" ? "Administrateur" : currentRole === "coach" ? "Coach" : currentRole === "parent" ? "Parent" : "Élève"} de l’Académie Delaveau</p><div class="form-grid"><button class="ghost-button" id="restart-tour">Revoir la visite guidée</button><button class="primary-button" id="logout-button">Se déconnecter</button></div>`; modal.classList.remove("hidden"); document.querySelector("#logout-button").onclick=logout; document.querySelector("#restart-tour").onclick=()=>{closeModal();startTour();}; }
function closeModal(){modal.classList.add("hidden");}
function bindStudentRows(){document.querySelectorAll("[data-student]").forEach(el=>el.onclick=()=>{selectedStudent=el.dataset.student;render();});}

const tourSteps = [ { selector:"#dashboard-stats",title:"Votre suivi en un regard",text:"Retrouvez ici les absences, les retards et le dernier bilan mensuel.",staffOnly:false }, { selector:'[data-view="monthly"]',title:"Le bilan mensuel",text:"Cet espace regroupera l’observation rédigée chaque mois par l’équipe." }, { selector:"#role-switch-button",title:"Votre profil",text:"Touchez ici pour revoir la visite ou vous déconnecter en toute sécurité." } ];
function relevantTourSteps(){return tourSteps.filter(step=>!step.staffOnly||currentRole!=="student").filter(step=>document.querySelector(step.selector));}
function maybeStartTour(){if(!currentUser||!authScreen.classList.contains("hidden"))return;if(!localStorage.getItem(`delaveau-tour-${currentRole}`))startTour();}
function startTour(){tourIndex=0;document.querySelector("#tour-layer").classList.remove("hidden");showTourStep();}
function showTourStep(){ const steps=relevantTourSteps(); if(tourIndex>=steps.length)return closeTour(true); const step=steps[tourIndex], target=document.querySelector(step.selector); if(!target){tourIndex++;return showTourStep();} target.scrollIntoView({behavior:"smooth",block:"center"}); setTimeout(()=>{ const rect=target.getBoundingClientRect(), focus=document.querySelector("#tour-focus"), card=document.querySelector("#tour-card"), margin=6; Object.assign(focus.style,{left:`${rect.left-margin}px`,top:`${rect.top-margin}px`,width:`${rect.width+margin*2}px`,height:`${rect.height+margin*2}px`}); document.querySelector("#tour-count").textContent=`Étape ${tourIndex+1} sur ${steps.length}`;document.querySelector("#tour-title").textContent=step.title;document.querySelector("#tour-text").textContent=step.text;document.querySelector("#tour-next").textContent=tourIndex===steps.length-1?"Terminer":"Suivant"; if(innerWidth>760){const below=rect.bottom+18,top=below+220<innerHeight?below:Math.max(15,rect.top-238),left=Math.min(innerWidth-345,Math.max(15,rect.left));Object.assign(card.style,{top:`${top}px`,left:`${left}px`});} },350); }
function closeTour(done=true){document.querySelector("#tour-layer").classList.add("hidden");if(done&&currentRole)localStorage.setItem(`delaveau-tour-${currentRole}`,"done");}

function scopedStudentId() { return currentRole === "student" || currentRole === "parent" ? currentUser.studentId : null; }
function countFor(list, studentId=null) { return studentId ? list.filter(item=>item.studentId===studentId).length : list.length; }
function studentRequests() { return state.absences.filter(item=>item.source==="student").sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date)); }
function requestCard(item) { const s=student(item.studentId),hasDocument=item.justification&&item.justification!=="Aucun justificatif"; return `<article class="request-item ${item.status==="À vérifier"?"request-pending":""}"><div class="request-item-head"><div class="request-person"><span class="avatar">${s?.initials||"?"}</span><div><span class="eyebrow">${dateFR(item.date)}</span><strong>${s?.name||"Élève"}</strong></div></div><span class="status ${item.status==="À vérifier"?"watch":item.status==="Refusée"?"alert":"good"}">${item.status||"À vérifier"}</span></div><p>${item.reason||item.text||"Aucun motif précisé"}</p><div class="request-meta"><span class="document-chip ${hasDocument?"attached":""}">${hasDocument?"▣ Justificatif joint":"◇ Sans justificatif"}</span><span>Demande élève</span></div><button class="secondary-button view-request" data-request="${item.id}">${item.status==="À vérifier"?"Examiner la demande":"Consulter la décision"} →</button></article>`; }
function bindRequestButtons() { document.querySelectorAll(".view-request").forEach(button=>button.onclick=()=>openRequestModal(button.dataset.request)); }
async function openRequestModal(id) {
  const item=state.absences.find(x=>x.id===id), s=item&&student(item.studentId); if(!item)return toast("Demande introuvable");
  const documentUrl=item.documentPath&&cloudConfigured?await signedDocumentUrl(item.documentPath):item.documentData;
  const documentView=documentUrl?item.documentType?.startsWith("image/")?`<img class="document-preview" src="${documentUrl}" alt="Justificatif de ${s?.name||"l’élève"}">`:`<iframe class="document-preview pdf-preview" src="${documentUrl}" title="Justificatif PDF"></iframe><a class="secondary-button document-link" href="${documentUrl}" target="_blank">Ouvrir le PDF</a>`:`<div class="document-empty">Aucun document joint à cette demande.</div>`;
  const decided=item.status!=="À vérifier";
  document.querySelector("#modal-content").innerHTML=`<div class="request-modal-head"><span class="avatar">${s?.initials||"?"}</span><div><span class="eyebrow">Demande d’absence</span><h2 id="modal-title">${s?.name||"Élève"}</h2><p class="modal-intro">${dateFR(item.date)}</p></div><span class="status ${item.status==="À vérifier"?"watch":item.status==="Refusée"?"alert":"good"}">${item.status}</span></div><div class="request-detail"><div><small>Motif déclaré</small><p>${item.reason||item.text||"—"}</p></div><div><small>Document transmis</small><strong>${item.justification||"Aucun justificatif"}</strong></div>${documentView}</div>${!decided?`<div class="decision-actions"><button class="ghost-button request-decision" data-status="Refusée">Refuser</button><button class="primary-button request-decision" data-status="Validée">Accepter l’absence</button></div>`:`<div class="decision-banner ${item.status==="Refusée"?"rejected":""}">Demande ${item.status.toLowerCase()}${item.reviewedBy?` par ${item.reviewedBy}`:""}.</div><button class="undo-decision request-decision" data-status="À vérifier">↶ Annuler cette décision et remettre en attente</button>`}`;
  modal.classList.remove("hidden");document.querySelectorAll(".request-decision").forEach(button=>button.onclick=async()=>{const newStatus=button.dataset.status,cloudStatus=newStatus==="Validée"?"approved":newStatus==="Refusée"?"rejected":"pending";button.disabled=true;if(cloudConfigured){await reviewAbsenceRequest(item.id,cloudStatus);await refreshCloudState();}else{item.status=newStatus;if(newStatus==="À vérifier"){delete item.reviewedBy;delete item.reviewedAt;}else{item.reviewedBy=currentUser.name;item.reviewedAt=todayISO();}state.notifications.filter(n=>n.requestId===item.id).forEach(n=>n.read=newStatus!=="À vérifier");save();}closeModal();toast(newStatus==="À vérifier"?"Décision annulée · demande remise en attente":`Demande ${newStatus.toLowerCase()}`);render();});
}
function renderSimpleDashboard() {
  const sid=scopedStudentId(), child=sid?student(sid):null, firstName=currentUser.name.split(" ")[0], absenceCount=countFor(state.absences,sid), delayCount=countFor(state.delays,sid), monthly=state.monthlyObservations.filter(item=>!sid||item.studentId===sid).sort((a,b)=>b.month.localeCompare(a.month));
  const title=currentRole==="parent"&&child?`Suivi de ${child.name}`:`Bonjour ${firstName}`;
  const subtitle=currentRole==="coach"||currentRole==="admin"?"Le suivi essentiel de l’Académie, sans informations inutiles.":"Absences, retards et bilan mensuel au même endroit.";
  app.innerHTML=heading("Académie Delaveau",title,subtitle)+`<section class="grid stats simple-stats" id="dashboard-stats">${statCard("Absences",absenceCount,"sur la période en cours","#b74d47")}${statCard("Retards",delayCount,"sur la période en cours","#c77d32")}${statCard("Bilans mensuels",monthly.length,monthly.length?`dernier : ${monthly[0].month}`:"aucun bilan publié","#23579a")}</section>${child?`<section class="card section-card horse-card"><div class="section-head"><div><span class="eyebrow">Mon partenaire</span><h2>${child.horse||"Cheval non renseigné"}</h2></div></div><div class="horse-details"><div><small>Âge</small><strong>${child.horseAge?`${child.horseAge} ans`:"—"}</strong></div><div><small>Taille</small><strong>${child.horseHeight?`${child.horseHeight} cm`:"—"}</strong></div><div><small>Ensemble depuis</small><strong>${child.horsePartnership||"—"}</strong></div><div class="horse-level"><small>Plus grande épreuve sautée</small><strong>${child.horseExperience||"—"}</strong></div></div></section>`:""}<section class="card section-card"><div class="section-head"><div><span class="eyebrow">Ce mois-ci</span><h2>Observation mensuelle</h2></div></div>${monthly.length?`<div class="observation"><p>${monthly[0].text}</p><small>${monthly[0].month} · ${monthly[0].author}</small></div>`:emptyBlock("✎","Aucune observation mensuelle","Le premier bilan apparaîtra ici lorsqu’il aura été rédigé.")}</section>`;
}
function renderTrackingSection(type) {
  const sid=scopedStudentId();
  const config={absences:{title:"Absences",subtitle:"Toutes les absences enregistrées.",list:state.absences,icon:"○",empty:"Aucune absence enregistrée"},delays:{title:"Retards",subtitle:"Tous les retards enregistrés.",list:state.delays,icon:"◷",empty:"Aucun retard enregistré"},monthly:{title:"Observations mensuelles",subtitle:"Un bilan clair de la progression chaque mois.",list:state.monthlyObservations,icon:"✎",empty:"Aucune observation mensuelle"}}[type];
  const items=config.list.filter(item=>!sid||item.studentId===sid).sort((a,b)=>(b.date||b.month||"").localeCompare(a.date||a.month||""));
  app.innerHTML=heading("Suivi",config.title,config.subtitle)+`<section class="card section-card">${items.length?items.map(item=>{const s=student(item.studentId);return `<div class="observation"><div class="observation-head"><strong>${s?s.name:currentUser.name}</strong><span class="status ${item.status==="À vérifier"?"warning":"good"}">${item.status||item.date||item.month}</span></div><p>${item.text||item.reason||""}</p><small>${item.date||item.month}${item.author?` · ${item.author}`:""}${item.justification?` · Justificatif : ${item.justification}`:""}</small></div>`}).join(""):emptyBlock(config.icon,config.empty,"Les nouvelles informations apparaîtront ici.")}</section>`;
}
function renderStaffHome() {
  const requests=studentRequests(), pending=requests.filter(item=>item.status==="À vérifier").length, unread=state.notifications.filter(item=>!item.read).length, firstName=currentUser.name.split(" ")[0];
  app.innerHTML=heading(currentRole==="admin"?"Administration":"Espace coach",`Bonjour ${firstName}`,"Une vue complète de l’effectif et des demandes à traiter.",`<button class="primary-button" id="quick-entry">+ Nouvelle saisie</button>`)+`<section class="grid stats simple-stats" id="dashboard-stats">${statCard("Élèves",state.students.length,"fiches accessibles","#23579a")}${statCard("Demandes",pending,"en attente de vérification","#c77d32")}${statCard("Alertes",unread,"non lues","#b74d47")}</section><section class="grid dashboard-grid"><article class="card section-card"><div class="section-head"><div><span class="eyebrow">Accès rapide</span><h2>Derniers élèves</h2></div><button class="text-button" id="all-students-button">Voir tous</button></div><div class="student-list">${state.students.slice(-3).reverse().map(studentRow).join("")||emptyBlock("♙","Aucun élève","Les inscriptions apparaîtront ici.")}</div></article><article class="card section-card"><div class="section-head"><div><span class="eyebrow">À traiter</span><h2>Demandes en cours</h2></div><button class="text-button" id="all-requests-button">Voir tout</button></div>${requests.filter(x=>x.status==="À vérifier").slice(0,3).map(requestCard).join("")||emptyBlock("♢","Aucune demande en attente","Les demandes des élèves apparaîtront ici.")}</article></section>`;
  document.querySelector("#quick-entry").onclick=()=>openStaffEntryModal();document.querySelector("#all-students-button").onclick=()=>{currentView="students";render();};document.querySelector("#all-requests-button").onclick=()=>{currentView="notifications";render();};bindStudentRows();bindRequestButtons();
}
function renderStudentSheet(id) {
  const s=student(id);if(!s){selectedStudent=null;return renderStudents();}const abs=state.absences.filter(x=>x.studentId===s.id),del=state.delays.filter(x=>x.studentId===s.id),monthly=state.monthlyObservations.filter(x=>x.studentId===s.id).sort((a,b)=>b.month.localeCompare(a.month));
  app.innerHTML=`<button class="ghost-button" id="back-to-students">← Toutes les fiches</button><section class="profile-sheet"><div class="profile-cover">${studentPortrait(s,"profile-avatar")}<div><span class="eyebrow">Fiche élève</span><h1>${s.name}</h1><p>${s.group} · ${s.email||"E-mail non renseigné"}</p></div><button class="primary-button" id="sheet-entry">+ Ajouter au suivi</button></div><div class="grid profile-grid"><article class="card section-card"><h2>Informations équestres</h2><div class="info-list"><div><small>Cheval</small><strong>${s.horse||"—"}</strong></div><div><small>Âge</small><strong>${s.horseAge?`${s.horseAge} ans`:"—"}</strong></div><div><small>Taille</small><strong>${s.horseHeight?`${s.horseHeight} cm`:"—"}</strong></div><div><small>Couple formé depuis</small><strong>${s.horsePartnership||"—"}</strong></div><div><small>Plus grande épreuve</small><strong>${s.horseExperience||"—"}</strong></div></div></article><article class="card section-card"><h2>Suivi</h2><div class="mini-kpis"><div><strong>${abs.length}</strong><small>Absences</small></div><div><strong>${del.length}</strong><small>Retards</small></div><div><strong>${monthly.length}</strong><small>Bilans</small></div></div>${monthly[0]?`<div class="latest-note"><small>Dernier bilan · ${monthly[0].month}</small><p>${monthly[0].text}</p></div>`:emptyBlock("✎","Aucun bilan","Aucune observation mensuelle.")}</article></div></section>`;
  document.querySelector("#back-to-students").onclick=()=>{selectedStudent=null;currentView="students";render();};document.querySelector("#sheet-entry").onclick=()=>openStaffEntryModal(s.id);
}
function openStaffEntryModal(preselect="") {
  if(!state.students.length)return toast("Aucun élève inscrit");
  document.querySelector("#modal-content").innerHTML=`<span class="eyebrow">Ajouter au suivi</span><h2 id="modal-title">Nouvelle saisie</h2><p class="modal-intro">Choisissez le type d’information et l’élève concerné.</p><form id="staff-entry-form" class="form-grid"><div class="field"><label>Élève</label><select id="entry-student">${state.students.map(s=>`<option value="${s.id}" ${Number(preselect)===s.id?'selected':''}>${s.name}</option>`).join("")}</select></div><div class="field"><label>Type</label><select id="entry-type"><option value="absence">Absence</option><option value="delay">Retard</option><option value="monthly">Observation mensuelle</option></select></div><div class="field"><label>Date</label><input id="entry-date" type="date" value="${todayISO()}" required></div><div class="field"><label>Détails</label><textarea id="entry-text" required placeholder="Ajoutez une information claire et factuelle…"></textarea></div><div class="form-actions"><button type="button" class="ghost-button" id="cancel-entry">Annuler</button><button class="primary-button">Enregistrer</button></div></form>`;
  modal.classList.remove("hidden");document.querySelector("#cancel-entry").onclick=closeModal;document.querySelector("#staff-entry-form").onsubmit=async e=>{e.preventDefault();const studentId=document.querySelector("#entry-student").value,type=document.querySelector("#entry-type").value,date=document.querySelector("#entry-date").value,text=document.querySelector("#entry-text").value.trim(),base={id:Date.now(),studentId,date,text,reason:text,author:currentUser.name,source:"staff",status:"Validée"};if(cloudConfigured){try{await createTrackingItem(type,{studentId,date,text});await refreshCloudState();closeModal();toast("Suivi mis à jour");return render();}catch(error){return toast(error.message||"Enregistrement impossible");}}if(type==="absence")state.absences.unshift(base);else if(type==="delay")state.delays.unshift(base);else state.monthlyObservations.unshift({...base,month:date.slice(0,7)});save();closeModal();toast("Suivi mis à jour");render();};
}
function readFileData(file) { return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}); }
function renderAbsenceRequest() {
  const s=student(currentUser.studentId);app.innerHTML=heading("Prévenir l’équipe","Déclarer une absence","Indique la date, le motif et ajoute un justificatif si tu en as un.")+`<section class="card section-card request-card"><form id="absence-request-form" class="form-grid"><div class="field"><label for="request-date">Date de l’absence</label><div class="date-control"><span class="date-display" id="request-date-display">${dateFR(todayISO())}</span><input id="request-date" type="date" min="${todayISO()}" value="${todayISO()}" required aria-label="Date de l’absence"></div></div><div class="field"><label for="request-reason">Motif</label><textarea id="request-reason" required placeholder="Exemple : rendez-vous médical…"></textarea></div><div class="field file-field"><span>Justificatif</span><input id="request-file" type="file" accept="image/*,.pdf"><label class="file-picker" for="request-file">＋ Ajouter une photo ou un PDF</label><small class="file-name" id="request-file-name">Aucun document sélectionné</small><small class="file-help">Facultatif · 5 Mo maximum</small></div><button class="primary-button">Envoyer à l’équipe</button></form></section>`;
  document.querySelector("#request-date").onchange=event=>{document.querySelector("#request-date-display").textContent=event.target.value?dateFR(event.target.value):"Choisir une date";};
  document.querySelector("#request-file").onchange=event=>{const file=event.target.files[0];document.querySelector("#request-file-name").textContent=file?file.name:"Aucun document sélectionné";};
  document.querySelector("#absence-request-form").onsubmit=async e=>{e.preventDefault();const submit=e.submitter,date=document.querySelector("#request-date").value,reason=document.querySelector("#request-reason").value.trim(),file=document.querySelector("#request-file").files[0];if(file&&file.size>5*1024*1024)return toast("Le justificatif doit faire moins de 5 Mo");submit.disabled=true;submit.textContent="Envoi…";try{if(cloudConfigured){await createAbsenceRequest({studentId:s.id,date,reason,file,userId:currentUser.userId});await refreshCloudState();toast("Demande envoyée aux coachs et admins");currentView="absences";return render();}const requestId=Date.now(),documentData=file?await readFileData(file):null;state.absences.unshift({id:requestId,studentId:s.id,date,createdAt:new Date().toISOString(),text:reason,reason,justification:file?.name||"Aucun justificatif",documentData,documentType:file?.type||null,author:s.name,source:"student",status:"À vérifier"});state.notifications.unshift({id:requestId+1,requestId,date:todayISO(),title:"Nouvelle demande d’absence",text:`${s.name} · ${date} · ${reason}${file?` · Justificatif : ${file.name}`:""}`,studentId:s.id,read:false});save();toast("Demande envoyée aux coachs et admins");currentView="absences";render();}catch(error){submit.disabled=false;submit.textContent="Envoyer à l’équipe";toast(error.message||"Le document n’a pas pu être enregistré");}};
}
function renderNotifications() { state.notifications.forEach(n=>n.read=true);save();const requests=studentRequests();app.innerHTML=heading("Équipe","Demandes d’absence","Consultez le motif et le justificatif, puis validez la demande.")+`<section class="request-grid">${requests.map(requestCard).join("")||emptyBlock("♢","Aucune demande","Les nouvelles demandes des élèves apparaîtront ici.")}</section>`;bindRequestButtons(); }
function renderEntryPage() { app.innerHTML=heading("Équipe","Ajouter au suivi","Enregistrez une absence, un retard ou une observation mensuelle.",`<button class="primary-button" id="open-entry">+ Nouvelle saisie</button>`)+`<section class="card section-card">${emptyBlock("+","Une saisie rapide","Choisissez un élève et le type d’information à ajouter à sa fiche.")}</section>`;document.querySelector("#open-entry").onclick=()=>openStaffEntryModal(); }
function render() { if(!currentUser)return renderAuthLanding(); document.body.classList.remove("auth-active"); authScreen.classList.add("hidden"); setProfile();renderNav(); if(selectedStudent&&(currentRole==="coach"||currentRole==="admin"))renderStudentSheet(selectedStudent);else if(currentView==="dashboard"&&(currentRole==="coach"||currentRole==="admin"))renderStaffHome();else if(currentView==="dashboard")renderSimpleDashboard();else if(currentView==="students"&&(currentRole==="admin"||currentRole==="coach"))renderStudents();else if(currentView==="entry"&&(currentRole==="admin"||currentRole==="coach"))renderEntryPage();else if(currentView==="notifications"&&(currentRole==="admin"||currentRole==="coach"))renderNotifications();else if(currentView==="request"&&currentRole==="student")renderAbsenceRequest();else if(["absences","delays","monthly"].includes(currentView))renderTrackingSection(currentView);else renderSimpleDashboard();renderNav(); }

document.querySelector("#role-switch-button").onclick=openAccountModal;
document.querySelector("#profile-button").onclick=openAccountModal;
document.querySelector("#modal-close").onclick=closeModal;
modal.onclick=event=>{if(event.target===modal)closeModal();};
document.querySelector("#global-search").oninput=event=>{if(currentRole==="student")return;const q=event.target.value.toLowerCase();if(q.length>1){currentView="students";renderStudents();document.querySelector("#all-students").innerHTML=state.students.filter(s=>s.name.toLowerCase().includes(q)).map(studentRow).join("")||emptyBlock("⌕","Aucun résultat","Essayez un autre nom.");bindStudentRows();renderNav();}};
document.querySelector("#tour-next").onclick=()=>{tourIndex++;showTourStep();};
document.querySelector("#tour-skip").onclick=()=>closeTour(true);
addEventListener("resize",()=>{if(!document.querySelector("#tour-layer").classList.contains("hidden"))showTourStep();});
async function boot(){if(cloudConfigured){try{const account=await currentCloudAccount();if(account){await refreshCloudState();const role=account.profile.role, pupil=role==="student"?state.students.find(s=>s.userId===account.profile.id):null;currentUser={name:account.profile.full_name,role,initials:initials(account.profile.full_name),studentId:pupil?.id||null,userId:account.profile.id};currentRole=role;persistSession(currentUser);}else{currentUser=null;currentRole=null;clearPersistentSession();}}catch(error){console.error("Supabase initialization",error);currentUser=null;currentRole=null;}}render();if(currentUser)setTimeout(()=>maybeStartTour(),600);}
await boot();
if("serviceWorker" in navigator&&location.hostname.endsWith("vercel.app")){navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister()));}else if("serviceWorker" in navigator&&location.protocol.startsWith("http")){navigator.serviceWorker.register("service-worker.js").catch(()=>{});}
